name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  GO_VERSION: "^1.18.1"

jobs:
  push_to_registry:
    name: Check out and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Run tests
        run: go test -v -race -cover ./...